name: Composer Install

inputs:
  op_service_account_token:
    required: true
    description: 1Password Service Account Token

runs:
  using: "composite"
  steps:
    - name: Configure PHP environment
      uses: shivammathur/setup-php@v2
      with:
        tools: composer:2
        php-version: '8.2'

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install 1Password CLI
      uses: 1password/install-cli-action@v1

    - name: Create auth.json via 1Password CLI
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ inputs.op_service_account_token }}
      run: |
        op user get --me
        op inject -i auth.template.json -o auth.json
      shell: bash

    - name: Install Composer
      run: |
        composer install --ignore-platform-reqs --optimize-autoloader --no-progress
        rm auth.json
      shell: bash
