name: Composer Install

inputs:
  OP_SERVICE_ACCOUNT_TOKEN:
    required: true
    description: 1Password service account token to use for populating composer auth.json
  OP_VAULT:
    required: true
    description: 1Password vault to use for populating composer auth.json
    default: 'Engineering'
  OP_ITEM:
    required: true
    description: 1Password item to use for populating composer auth.json
    default: 'MT-Composer-Auth'

runs:
  using: "composite"
  steps:
    - name: Configure PHP environment
      uses: shivammathur/setup-php@v2
      with:
        tools: composer:2
        php-version: '8.2'

    - name: Get Composer Cache Directory
      id: composer-cache
      shell: bash
      run: |
        echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install 1Password CLI
      uses: 1password/install-cli-action@v1

    - name: Create auth.json via 1Password CLI
      shell: bash
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ inputs.OP_SERVICE_ACCOUNT_TOKEN }}
        OP_VAULT: ${{ inputs.OP_VAULT }}
        OP_ITEM: ${{ inputs.OP_ITEM }}
      run: |
        op user get --me
        op inject -i auth.template.json -o auth.json
    - name: Install Composer
      shell: bash
      run: |
        composer install --ignore-platform-reqs --optimize-autoloader --no-progress
        rm auth.json
