name: 'Code Quality Checks'

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
      - develop

jobs:
  coding-standards:
    name: 'Coding Standards'
    uses: ./.github/workflows/phpcs.yml

  linting:
    name: 'Linting'
    uses: ./.github/workflows/linting.yml

  phpstan:
    name: 'Static Analysis'
    needs: [coding-standards, linting]
    uses: ./.github/workflows/static-analysis.yml

# Enable this job if you have PHPUnit tests
# slic:
#   name: 'PHP Tests'
#   needs: [coding-standards, phpstan, linting]
#   uses: ./.github/workflows/php-tests.yml
