name: 'Code Quality Checks'

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
      - develop
  env:
    OP_VAULT: 'vob6y2d3l6ohybeuefe3uly2l4'
    OP_ITEM: 'Test-Composer-Auth'

jobs:
  coding-standards:
    name: 'Coding Standards'
    uses: ./.github/workflows/phpcs.yml
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

  linting:
    name: 'Linting'
    uses: ./.github/workflows/linting.yml

  phpstan:
    name: 'Static Analysis'
    needs: [coding-standards, linting]
    uses: ./.github/workflows/static-analysis.yml
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

# Enable this job if you have PHPUnit tests
# slic:
#   name: 'PHP Tests'
#   needs: [coding-standards, phpstan, linting]
#   uses: ./.github/workflows/php-tests.yml
#   secrets:
#     OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
