
name: Dokku Deploy Dev

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy_app:
    uses: ./.github/workflows/pipeline-dokku.yml
    with:
      app_name: moose-dev
      branch: ${{ github.ref }}
      server: d1.moderntribe.qa
      is_review_app: false
    secrets:
      github_pat_token: ${{ secrets.GH_BOT_TOKEN }}
      ssh_private_key: ${{ secrets.DOKKU_DEPLOY_KEY }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
      ONEPASS_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONEPASS_SERVICE_ACCOUNT_TOKEN }}
      ONEPASS_VAULT: ${{ secrets.ONEPASS_VAULT }}
      ONEPASS_ITEM: ${{ secrets.ONEPASS_ITEM }}
