name: Coding Standards

on:
  workflow_call:
    secrets:
      op_service_account_token:
        required: true

jobs:
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect File Changes
        uses: dorny/paths-filter@v3
        id: changed-files
        with:
          list-files: shell
          filters: |
            phpcs:
              - added|modified: 'wp-content/plugins/core/**/*.php'
              - added|modified: 'wp-content/themes/core/**/*.php'
              - added|modified: 'wp-content/mu-plugins/**/*.php'
              - added|modified: 'phpcs.xml.dist'

      - name: Composer Install
        # if: steps.changed-files.outputs.phpcs == 'true'
        uses: ./.github/actions/composer-install
        with:
          op_service_account_token: ${{ secrets.op_service_account_token }}

      - name: Run PHPCS
        if: steps.changed-files.outputs.phpcs == 'true'
        run: |
          composer phpcs
