name: Coding Standards

on:
  workflow_call:
    inputs:
      OP_VAULT:
        type: string
        description: 1Password vault to use for populating composer auth.json
      OP_ITEM:
        type: string
        description: 1Password item to use for populating composer auth.json
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        required: true
        description: 1Password Service Account Token to use for populating composer auth.json

jobs:
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect File Changes
        uses: dorny/paths-filter@v3
        id: changed-files
        with:
          list-files: shell
          filters: |
            phpcs:
              - added|modified: 'wp-content/plugins/core/**/*.php'
              - added|modified: 'wp-content/themes/core/**/*.php'
              - added|modified: 'wp-content/mu-plugins/**/*.php'
              - added|modified: 'phpcs.xml.dist'

      - name: Composer Install
        # if: steps.changed-files.outputs.phpcs == 'true'
        uses: ./.github/actions/composer-install
        with:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          OP_VAULT: 'test-vault' #${{ inputs.OP_VAULT }}
          OP_ITEM: ${{ inputs.OP_ITEM }}

      - name: Run PHPCS
        # if: steps.changed-files.outputs.phpcs == 'true'
        run: |
          composer phpcs
