name: Static Analysis

on:
  workflow_call:

jobs:
  phpstsan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Detect File Changes
        uses: dorny/paths-filter@v3
        id: changed-files
        with:
          list-files: shell
          filters: |
            phpstan:
              - added|modified: 'wp-content/plugins/core/**/*.php'
              - added|modified: 'wp-content/themes/core/**/*.php'
              - added|modified: 'wp-content/mu-plugins/**/*.php'
              - added|modified: 'phpstan.neon.dist'

      - name: Composer Install
        if: steps.changed-files.outputs.phpcs == 'true'
        uses: ./.github/actions/composer-install
        with:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          OP_VAULT: ${{ secrets.OP_VAULT }}
          OP_ITEM: ${{ secrets.OP_ITEM }}

      - name: Run PHPStan static analysis
        if: steps.changed-files.outputs.phpstan == 'true'
        run: composer phpstan
