name: Static Analysis

on:
  workflow_call:
    secrets:
      ONEPASS_SERVICE_ACCOUNT_TOKEN:
        required: true
        description: '1Password Service Account Token to use for populating composer auth.json'
      ONEPASS_VAULT:
        description: '1Password vault to use for populating composer auth.json'
      ONEPASS_ITEM:
        description: '1Password item to use for populating composer auth.json'

jobs:
  phpstsan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Detect file changes'
        uses: dorny/paths-filter@v3
        id: changed-files
        with:
          list-files: shell
          filters: |
            phpstan:
              - added|modified: 'wp-content/plugins/core/**/*.php'
              - added|modified: 'wp-content/themes/core/**/*.php'
              - added|modified: 'wp-content/mu-plugins/**/*.php'
              - added|modified: 'phpstan.neon.dist'

      - name: 'Composer install'
        if: steps.changed-files.outputs.phpstan == 'true'
        uses: ./.github/actions/composer-install
        with:
          COMPOSER_INSTALL_FLAGS: '--optimize-autoloader'
          ONEPASS_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONEPASS_SERVICE_ACCOUNT_TOKEN }}
          ONEPASS_VAULT: ${{ secrets.ONEPASS_VAULT }}
          ONEPASS_ITEM: ${{ secrets.ONEPASS_ITEM }}

      - name: 'Run PHPStan static analysis'
        if: steps.changed-files.outputs.phpstan == 'true'
        run: composer phpstan
